name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main # change this to 'master' if necessary!
  pull_request:

jobs:
  # The CI test job
  test:
    name: CI test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap-for-packages@v1
      - uses: gap-actions/run-test-for-packages@v1
